### ISSUE TITLE
Build the maverick executable ERROR - undefined reference to `gpioTime'

### ISSUE THREAD

**Issue by tommcm1200** [eightywon/maverick#5]
Hi mate,

Encountering an error when building the maverick executable.  Any suggestions towards debugging would be much appreciated.

Thx.

```
pi@raspberrypi:~/maverick $ sudo gcc -o /var/www/html/maverick maverick.c -lwiringPi -lsqlite3
/tmp/ccmKPswO.o: In function `outputData':
maverick.c:(.text+0x1fc): undefined reference to `gpioTime'
/tmp/ccmKPswO.o: In function `readPin':
maverick.c:(.text+0x898): undefined reference to `gpioTime'
/tmp/ccmKPswO.o: In function `main':
maverick.c:(.text+0x122c): undefined reference to `gpioInitialise'
maverick.c:(.text+0x1264): undefined reference to `gpioSetAlertFunc'
maverick.c:(.text+0x14d8): undefined reference to `gpioDelay'
collect2: error: ld returned 1 exit status
```

**Comment by eightywon** [comment]
I changed the maverick executable to use [PIGPIO ](http://abyz.me.uk/rpi/pigpio/download.html) instead of wiringPi, but forgot to update the build instructions in the readme.

Try:

pi@raspberrypi:~/maverick $ sudo gcc -o /var/www/html/maverick maverick.c **-lpigpio** -lsqlite3

Updating the readme now
